### ISSUE TITLE
seems unable to handle/parse complex html

### ISSUE THREAD

**Issue by mo-han** [svsool/vscode-markdown-kit#2]
was trying to use your "memo" extension, installed this one as well.

copied something like this (readme page of this repo) and pasted into vscode, and this extension works fine:
![图片](https://user-images.githubusercontent.com/9916948/116659528-4dddd580-a9c4-11eb-9c59-e5b02146b395.png)
![图片](https://user-images.githubusercontent.com/9916948/116659567-6221d280-a9c4-11eb-91e4-a57e878a91e8.png)

then tried to copy something from [知乎](https://www.zhihu.com/) and pasted into vscode, this extension failed with error:
![图片](https://user-images.githubusercontent.com/9916948/116659872-d0669500-a9c4-11eb-915c-3410a5910e1d.png)
![图片](https://user-images.githubusercontent.com/9916948/116659931-e5dbbf00-a9c4-11eb-8a45-89600bff0973.png)

**Comment by svsool** [comment]
Hi,

It would be great if you could look into the problem and contribute.

I'm not a zhihu user.

Thank you!
